name: 'atime-versions'
description: 'Use atime_versions() to compare performance between versions'
author: 'Jane He'

runs:
  using: "composite"
  steps:
    - name: check-out
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: setup
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - name: setup-dependency
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: any::rcmdcheck, any::devtools, any::ggplot2, any::directlabels
        needs: check

    - name: atime pkg
      id: atime-pkg
      env:
        _R_CHECK_CRAN_INCOMING_: false
      run: |
        ## --------------------------------------------------------------------
        devtools::install_github("tdhock/atime@compare-dt-tidy")

        src_dir <- Sys.getenv("GITHUB_WORKSPACE")

        options(repos="http://cloud.r-project.org")
        result.list <- atime::atime_pkg(src_dir)
        # apply t.test to each of the expression, between HEAD and CRAN
        detect_perf_change <- function(expr, alpha=1e-3){
          measure <- expr$measurements
          head_perf <- measure[startsWith(measure$expr.name, "HEAD"), mean]
          cran_perf <- measure[startsWith(measure$expr.name, "CRAN"), mean]
          test_result  <- t.test(head_perf, cran_perf, paired = FALSE)
          return (test_result$p.value < alpha)
        }

        sig_changes <- result.list[unlist(lapply(result.list, detect_perf_change, 0.6))]
        
        out_str <- paste("Significant performance changes detected in ", names(sig_changes))
        out_str <- paste(out_str, collapse = "\n")
        cat(sprintf("ATIME_PKG_RESULT='%s'\n", out_str), file = Sys.getenv("GITHUB_ENV"), append = TRUE)
        

        
      shell: Rscript {0}
      working-directory: ${{ inputs.working-directory }}

    - name: upload-artifact
      uses: actions/upload-artifact@v3
      with:
        name: atime-results
        path: inst/atime/

    - name: PR comment with file
      # if: steps.atime_pkg.outputs.atime-pkg-result

      uses: thollander/actions-comment-pull-request@v2
      with:
        message: ${{env.ATIME_PKG_RESULT}}



