name: 'atime-versions'
description: 'Use atime_versions() to compare performance between versions'
author: 'Jane He'
inputs:

runs:
  using: "composite"
  steps:
    - name: atime-versions
      id: atime-verions  
      env:
        _R_CHECK_CRAN_INCOMING_: false
      run: |
        ## --------------------------------------------------------------------
      
        tdir <- Sys.getenv("GITHUB_WORKSPACE")
        atime.list <- atime::atime_versions(
          pkg.path=tdir,
          N=2^seq(2, 20),
          setup={
            quantmod::getSymbols('AAPL')
            closing_prices <- quantmod::Cl(AAPL)
          },
          expr=mean(closing_prices),
          "latest"=Sys.getenv("GITHUB_SHA"),
          "previous"="3181693822101e1e60c3e6fcb27fd9459424a634")
        refs.best <- atime::references_best(atime.list)
        plot(refs.best)
        atime::atime_versions_remove("quantmod")
        
      shell: Rscript {0}
      working-directory: ${{ inputs.working-directory }}


