name: 'atime-versions'
description: 'Use atime_versions() to compare performance between versions'
author: 'Jane He'

runs:
  using: "composite"
  steps:
    - name: check-out
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: setup
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - name: setup-dependency
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: any::rcmdcheck, any::devtools, any::ggplot2, any::directlabels
        needs: check

    - name: atime-versions
      id: atime-verions  
      env:
        _R_CHECK_CRAN_INCOMING_: false
      run: |
        ## --------------------------------------------------------------------
        devtools::install_github("tdhock/atime@compare-dt-tidy")
        src_dir <- Sys.getenv("GITHUB_WORKSPACE")
        atime.list <- atime::atime_versions(
          pkg.path=src_dir,
          N=2^seq(2, 20),
          setup={
            quantmod::getSymbols('AAPL')
            closing_prices <- quantmod::Cl(AAPL)
          },
          expr=mean(closing_prices),
          "latest"=Sys.getenv("GITHUB_SHA"),
          "previous"="3181693822101e1e60c3e6fcb27fd9459424a634")
        refs.best <- atime::references_best(atime.list)
        plot(refs.best)
        atime::atime_versions_remove("quantmod")
        
      shell: Rscript {0}
      working-directory: ${{ inputs.working-directory }}


