name: 'atime-versions'
description: 'Use atime_versions() to compare performance between versions'
author: 'Jane He'

runs:
  using: "composite"
  steps:
    - name: check-out
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: setup
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - name: setup-dependency
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: any::rcmdcheck, any::devtools, any::ggplot2, any::directlabels
        needs: check

    - name: atime-versions
      id: atime-verions  
      env:
        _R_CHECK_CRAN_INCOMING_: false
      run: |
        ## --------------------------------------------------------------------
        devtools::install_github("tdhock/atime@compare-dt-tidy")

        knitr::opts_chunk$set(
          collapse = TRUE,
          comment = "#>"
        )

        src_dir <- Sys.getenv("GITHUB_WORKSPACE")
        inst.atime <- file.path(src_dir, "inst", "atime")
        test.lines <- readLines(file.path(inst.atime, "tests.R"))
        cat(test.lines, sep="\n")

        options(repos="http://cloud.r-project.org")
        result.list <- atime::atime_pkg(src_dir)
        # tests.png <- file.path(inst.atime, "tests_all_facet.png")
        # knitr::include_graphics(tests.png)
        
      shell: Rscript {0}
      working-directory: ${{ inputs.working-directory }}


